teacher:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 127.0.0.1
    port: 13306
    database: mb
    username: root
    password: 123456
  #阿里云配置
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucket-name: java-aitwo
    region: cn-beijing